title: Long Haul
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "page/:num"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   youtube: ngaoduky
   instagram: ngaoduky
   twitter: ngaoduky
   facebook: ngaoduky.com
   email: ngaoduky.com@gmail.com

google_analytics: "UA-58263416-1"
